spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa

spring.h2.console.path=/h2
spring.h2.console.enabled=true

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

# Use X-Forwarded-* headers when behind proxy (e.g. Docker port mapping, reverse proxy)
server.forward-headers-strategy=framework
